Tensors are multidimensional arrays. And PyTorch tensors are similar to NumPy’s n-dimensional arrays. We can use these tensors on a GPU as well (this is not the case with NumPy arrays). This is a major advantage of using tensors.

PyTorch supports multiple types of tensors, including:

FloatTensor: 32-bit float

DoubleTensor: 64-bit float

HalfTensor: 16-bit float

IntTensor: 32-bit int

LongTensor: 64-bit int

Now, let’s look at the basics of PyTorch along with how it compares against NumPy.

In [1]:
import numpy as np
import torch

In [2]:
#initializing 2 arrays
a= np.array(2)
b= np.array(1)

print(a,b)


2 1


In [3]:
#addition
print(a+b)

3


In [4]:
#substraction
print(a-b)

1


In [5]:
#multiplication
print(a*b)

2


In [6]:
print(a/b)

2.0


In [7]:
#initializing 2 tensors
a= torch.tensor(2)
b=torch.tensor(1)

In [8]:
print(a,b)

tensor(2) tensor(1)


In [9]:
#addition
print(a+b)

tensor(3)


In [10]:
print(a-b)

tensor(1)


In [11]:
print(a*b)

tensor(2)


In [12]:
print(a/b)

tensor(2)


In [13]:
#matrix of zeros using numpy
a=np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [14]:
#matrix of zeros using pytorch
a=torch.zeros((3,3))
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [15]:
# setting ramdom seed for numpy
np.random.seed(42)
#matrix of random number
a=np.random.randn(3,3) # generates random number that follow normal distribution
a

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [16]:
# setting random seed for pytorch
torch.manual_seed(42)
#matrix of random number
a= torch.randn(3,3)
a

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [17]:
#setting the random seed for numpy and initializing two matrix
np.random.seed(42)
a=np.random.randn(3,3)
b=np.random.randn(3,3)
print(a)
print(b)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
[[ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733]]


In [18]:
#matrix addition
print(np.add(a,b),'\n')

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]] 



In [19]:
#matrix subtraction
print(np.subtract(a,b),'\n')

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]] 



In [20]:
#matrix multiplication
print(np.dot(a,b),'\n')

[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]] 



In [21]:
#matrix division
print(np.divide(a,b),'\n')

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]] 



In [22]:
# matrix transpose
print('original : \n', a)
print('transpose : \n', a.transpose())

original : 
 [[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
transpose : 
 [[ 0.49671415  1.52302986  1.57921282]
 [-0.1382643  -0.23415337  0.76743473]
 [ 0.64768854 -0.23413696 -0.46947439]]


In [23]:
#setting up the random seed for pytorch and initializing two matrix
torch.manual_seed(42)
a= torch.randn(3,3)
b= torch.randn(3,3)
print(a,'\n',b,'\n')

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 
 tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]]) 



In [24]:
#matrix addition
print(torch.add(a,b),'\n')

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 



In [25]:
#matrix subtraction
print(torch.sub(a,b),'\n')

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 



In [27]:
#matrix multiplication
print(torch.mm(a,b),'\n')

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 



In [28]:
#matrix division
print(torch.div(a,b),'\n')

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]]) 



In [29]:
# matrix transpose
print('original : \n', a)
print('transpose : \n', a.t())

original : 
 tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])
transpose : 
 tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])


# Concatenating Tensors

In [30]:

# initializing two tensors
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(a, '\n')
print(b)

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])


In [31]:
# concatenating vertically
torch.cat((a,b))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [32]:
# concatenating horizontally
torch.cat((a,b),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

# Reshaping Tensors

In [33]:
# setting the random seed for pytorch
torch.manual_seed(42)
# initializing tensor
a = torch.randn(2,4)
print(a)
a.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([2, 4])

In [35]:

# reshaping tensor
b = a.reshape(1,8)
print(b)
b.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([1, 8])

In [38]:
a.shape

(2, 2)

In [39]:
# initializing a numpy array
a = np.array([[1,2],[3,4]])
print(a, '\n')

# converting the numpy array to tensor
tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


# Autograd Module

PyTorch uses a technique called automatic differentiation. It records all the operations that we are performing and replays it backward to compute gradients. This technique helps us to save time on each epoch as we are calculating the gradients on the forward pass itself.

In [40]:
# initializing a tensor
a = torch.ones((2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [41]:

# performing operations on the tensor
b = a + 5
c = b.mean()
print(b,c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


First of all, we added 5 to all the elements of this tensor and then taken the mean of that tensor. We will first manually calculate the gradients and then verify that using PyTorch. We performed the following operations on a:

b = a + 5

c = mean(b) = Σ(a+5) / 4

Now, the derivative of c w.r.t. a will be ¼ and hence the gradient matrix will be 0.25. Let’s verify this using PyTorch:

In [42]:
# back propagating
c.backward()

# computing gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


# Optim Module

In [12]:
# importing the optim module
from torch import optim

# adam
## adam = optim.Adam(model.parameters(), lr=learning_rate)

# sgd
## SGD = optim.SGD(model.parameters(), lr=learning_rate)

# Building a Neural Network from Scratch in PyTorch

In [43]:
#Input tensor
X = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y = torch.Tensor([[1],[1],[0]])

print(X, '\n')
print(y)

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]]) 

tensor([[1.],
        [1.],
        [0.]])


In [44]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + torch.exp(-x))

#Derivative of Sigmoid Function/
def derivatives_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [45]:
#Variable initialization

epoch=7000 #Setting training iterations
lr=0.1 #Setting learning rate

inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layer neurons
output_neurons = 1 #number of neurons in output layer

#weight and bias initialization
wh=torch.randn(inputlayer_neurons, hiddenlayer_neurons).type(torch.FloatTensor)
bh=torch.randn(1, hiddenlayer_neurons).type(torch.FloatTensor)
wout=torch.randn(hiddenlayer_neurons, output_neurons)
bout=torch.randn(1, output_neurons)

In [46]:
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1 = torch.mm(X, wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hidden_layer_activations = sigmoid(hidden_layer_input)

    output_layer_input1 = torch.mm(hidden_layer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = torch.mm(d_output, wout.t())
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
    bout += d_output.sum() *lr
    wh += torch.mm(X.t(), d_hiddenlayer) *lr
    bh += d_output.sum() *lr

In [47]:
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 tensor([[1.],
        [1.],
        [0.]]) 

predicted :
 tensor([[0.9980],
        [0.9964],
        [0.0053]])
