In [1]:
import torch

In [2]:
torch.__version__

'1.1.0'

In [3]:
import torch.nn as nn
import numpy as np
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
data = pd.read_csv("datasets/iris.csv")

In [6]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [7]:
data['target'].value_counts()

2.0    50
1.0    50
0.0    50
Name: target, dtype: int64

In [8]:
X = data.drop("target",axis = 1).values

In [9]:
Y = data['target'].values

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=33)

In [11]:
X_train.shape

(120, 4)

In [12]:
X_train[0:5]

array([[5.6, 2.7, 4.2, 1.3],
       [6.7, 3.1, 4.7, 1.5],
       [5.6, 2.8, 4.9, 2. ],
       [6.4, 3.2, 5.3, 2.3],
       [6.7, 3.1, 5.6, 2.4]])

In [13]:
Y_train[0:5]

array([1., 1., 2., 2., 2.])

In [14]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

#another way of converting numpy array to tensor
#X_train = torch.tensor(X_train, dtype=torch.float)
#X_test = torch.tensor(X_test, dtype=torch.float)

In [15]:
X_train[0:5]

tensor([[5.6000, 2.7000, 4.2000, 1.3000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [5.6000, 2.8000, 4.9000, 2.0000],
        [6.4000, 3.2000, 5.3000, 2.3000],
        [6.7000, 3.1000, 5.6000, 2.4000]])

In [16]:
X_test[0:5]

tensor([[5.7000, 2.9000, 4.2000, 1.3000],
        [6.7000, 3.1000, 4.4000, 1.4000],
        [4.7000, 3.2000, 1.6000, 0.2000],
        [6.5000, 2.8000, 4.6000, 1.5000],
        [6.1000, 2.6000, 5.6000, 1.4000]])

In [17]:
Y_train = torch.LongTensor(Y_train)
Y_test = torch.LongTensor(Y_test)

In [18]:
Y_train[0:5]

tensor([1, 1, 2, 2, 2])

In [19]:
Y_test[0:5]

tensor([1, 1, 0, 1, 2])

In [20]:
from torch.utils.data import TensorDataset, DataLoader

In [21]:
dataset = TensorDataset(X_train, Y_train)

In [22]:
train_loader = DataLoader(dataset, batch_size=10)

In [23]:
for data in train_loader:
    break

In [24]:
data[0]

tensor([[5.6000, 2.7000, 4.2000, 1.3000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [5.6000, 2.8000, 4.9000, 2.0000],
        [6.4000, 3.2000, 5.3000, 2.3000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [5.7000, 3.0000, 4.2000, 1.2000],
        [5.0000, 2.3000, 3.3000, 1.0000],
        [4.9000, 3.1000, 1.5000, 0.1000]])

In [25]:
data[1]

tensor([1, 1, 2, 2, 2, 2, 2, 1, 1, 0])

In [26]:
abc, xyz = data

In [27]:
abc

tensor([[5.6000, 2.7000, 4.2000, 1.3000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [5.6000, 2.8000, 4.9000, 2.0000],
        [6.4000, 3.2000, 5.3000, 2.3000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [5.7000, 3.0000, 4.2000, 1.2000],
        [5.0000, 2.3000, 3.3000, 1.0000],
        [4.9000, 3.1000, 1.5000, 0.1000]])

In [28]:
xyz

tensor([1, 1, 2, 2, 2, 2, 2, 1, 1, 0])

# Neural network structure

In [29]:
#input features = 4 
#output =3
#(3+4)/2 = 3.5

In [30]:
import torch.nn as nn
# 4 -> 8 -> 9 -> 3
network = nn.Sequential(nn.Linear(in_features=4, out_features=8),
                        nn.ReLU(),
                        nn.Linear(8, 9),
                        nn.ReLU(),
                        nn.Linear(9, 3)
                        
                        )

In [31]:
# network.parameters

In [32]:
loss_function = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(network.parameters(), lr=0.01)

In [33]:
len(train_loader)

12

In [34]:
epochs = 300
Losses = []

for epoch in range(epochs):
  Loss = 0

  for data in train_loader:
    inputs, outputs = data
    #print(inputs)
    #print('-----')
    #print(outputs)
    
    predictions = network.forward(inputs) 
    loss = loss_function(predictions, outputs)
    Loss = Loss + loss.item()
    
    optimizer.zero_grad() 
    loss.backward()
    optimizer.step()


  if epoch % 10 ==1:
    print('Epoch: ' + str(epoch) + ' loss: ' + str(Loss / len(train_loader)))

Epoch: 1 loss: 0.7255029082298279
Epoch: 11 loss: 0.14700146578252316
Epoch: 21 loss: 0.10748241034646829
Epoch: 31 loss: 0.09551881335210055
Epoch: 41 loss: 0.08906123697912942
Epoch: 51 loss: 0.08529829781036824
Epoch: 61 loss: 0.08143976328816886
Epoch: 71 loss: 0.07899343882066508
Epoch: 81 loss: 0.07706630207637015
Epoch: 91 loss: 0.07548464101273566
Epoch: 101 loss: 0.07433819683501497
Epoch: 111 loss: 0.07327980807167478
Epoch: 121 loss: 0.07236137974541634
Epoch: 131 loss: 0.07157211673135559
Epoch: 141 loss: 0.07072907319525257
Epoch: 151 loss: 0.0702347225160338
Epoch: 161 loss: 0.06946261072880588
Epoch: 171 loss: 0.0689631290442776
Epoch: 181 loss: 0.06838585290824994
Epoch: 191 loss: 0.0679333207954187
Epoch: 201 loss: 0.06751269545444909
Epoch: 211 loss: 0.06707229698076844
Epoch: 221 loss: 0.06679919070059744
Epoch: 231 loss: 0.06647757423343137
Epoch: 241 loss: 0.06603852048283443
Epoch: 251 loss: 0.0655233573440152
Epoch: 261 loss: 0.0652797847869806
Epoch: 271 loss: 0

In [36]:
predictions = network.forward(X_test)
predictions

tensor([[ -6.1674,   3.2942,  -3.5165],
        [ -7.0539,   3.7779,  -4.0192],
        [  4.3758,  -7.1945, -12.5618],
        [ -7.9099,   2.1783,  -2.1279],
        [-10.6158,  -1.5695,   2.1192],
        [-13.4513,  -3.0699,   3.9871],
        [  4.1638,  -6.8476, -12.3358],
        [  4.9709,  -8.1461, -13.5907],
        [-10.7551,  -1.4791,   2.0634],
        [-12.7382,  -2.8849,   3.7290],
        [-13.1316,  -3.0032,   3.8834],
        [  4.5166,  -7.4392, -12.5572],
        [-12.1836,  -2.6819,   3.4848],
        [ -7.6948,   1.9478,  -1.9057],
        [-11.1499,  -1.6069,   2.2841],
        [ -6.7774,   3.6923,  -3.9545],
        [ -8.9435,   0.0363,   0.2965],
        [  5.0533,  -8.2792, -13.7769],
        [ -7.6778,   2.2086,  -2.1768],
        [-12.0699,  -1.8195,   2.5208],
        [  4.6968,  -7.7073, -13.1387],
        [  5.0401,  -8.2442, -14.0831],
        [-12.7588,  -2.8852,   3.7328],
        [  4.7058,  -7.7256, -13.0894],
        [ -9.8599,  -1.0138,   1.4839],


In [37]:
correct = 0
with torch.no_grad():
    for i,data in enumerate(X_test):
        Y_Pred = network.forward(data)
        print(f'{i+1:2}. {str(Y_Pred):38}  {Y_test[i]}')
        if Y_Pred.argmax().item() == Y_test[i]:
            correct += 1
print(f'\n{correct} out of {len(Y_test)} = {100*correct/len(Y_test):.2f}% correct')

 1. tensor([-6.1674,  3.2942, -3.5165])     1
 2. tensor([-7.0539,  3.7779, -4.0192])     1
 3. tensor([  4.3758,  -7.1945, -12.5618])  0
 4. tensor([-7.9099,  2.1783, -2.1279])     1
 5. tensor([-10.6158,  -1.5695,   2.1192])  2
 6. tensor([-13.4513,  -3.0699,   3.9871])  2
 7. tensor([  4.1638,  -6.8476, -12.3358])  0
 8. tensor([  4.9709,  -8.1461, -13.5907])  0
 9. tensor([-10.7551,  -1.4791,   2.0634])  2
10. tensor([-12.7382,  -2.8849,   3.7290])  2
11. tensor([-13.1316,  -3.0032,   3.8834])  2
12. tensor([  4.5166,  -7.4392, -12.5572])  0
13. tensor([-12.1836,  -2.6819,   3.4848])  2
14. tensor([-7.6948,  1.9478, -1.9057])     1
15. tensor([-11.1499,  -1.6069,   2.2841])  2
16. tensor([-6.7774,  3.6923, -3.9545])     1
17. tensor([-8.9435,  0.0363,  0.2965])     2
18. tensor([  5.0533,  -8.2792, -13.7769])  0
19. tensor([-7.6778,  2.2086, -2.1768])     1
20. tensor([-12.0699,  -1.8195,   2.5208])  2
21. tensor([  4.6968,  -7.7073, -13.1387])  0
22. tensor([  5.0401,  -8.2442, -1