In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.8.0'

In [7]:
dataset = pd.read_excel('datasets/Folds5x2_pp.xlsx')

In [8]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [16]:
x = dataset.iloc[:,:-1].values

In [18]:
y = dataset.iloc[:,-1].values

In [20]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=123)

Initialize artifical neural netwoek

In [25]:
ann = tf.keras.models.Sequential()

Add input and first hidden layer



In [27]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

Add second hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

Add ouput layer

In [29]:
ann.add(tf.keras.layers.Dense(units = 1))

In [1]:
ann.compile(loss="mean_squared_error",optimizer="adam")

In [49]:
ann.fit(x_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 25.8944
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 25.9350
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 26.2148
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 25.8383
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 26.2938
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 25.8013
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 25.6902
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 25.7801
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 25.8265
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 25.6987
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 25.9594
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 25.8764
E

In [50]:
y_pred = ann.predict(x_test)
y_pred

array([[452.26],
       [440.46],
       [472.69],
       ...,
       [439.87],
       [448.61],
       [484.06]], dtype=float32)

In [51]:
y_pred.shape

(1914, 1)

In [52]:
np.set_printoptions(precision=2)
y_pred.reshape(len(y_pred),1)

array([[452.26],
       [440.46],
       [472.69],
       ...,
       [439.87],
       [448.61],
       [484.06]], dtype=float32)

In [53]:
y_pred.shape

(1914, 1)

In [54]:
y_test.shape

(1914,)

In [55]:
y_test.reshape(len(y_test),1)

array([[455.41],
       [441.64],
       [471.63],
       ...,
       [430.2 ],
       [441.58],
       [493.72]])

In [56]:
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis=1)

array([[452.26, 455.41],
       [440.46, 441.64],
       [472.69, 471.63],
       ...,
       [439.87, 430.2 ],
       [448.61, 441.58],
       [484.06, 493.72]])